# Generated by Django 5.0.14 on 2026-09-17 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('graduation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('ATOMIC', 'Atomic'), ('PARTIAL', 'Partial')], max_length=20)),
                ('inserted', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='graduation.graduationbatch')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('row_number', models.IntegerField()),
                ('student_code', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('SKIP', 'Skip'), ('ERROR', 'Error')], max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='students.importbatch')),
            ],
            options={
                'db_table': 'students_import_batch_item',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('student_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1)),
                ('national_id', models.CharField(blank=True, help_text='Số CCCD/CMND, dùng để đối chiếu khi cấp văn bằng.', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('enrollment_year', models.PositiveIntegerField(blank=True, help_text='Năm nhập học, vd: 2020', null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.faculty')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.major')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students_student',
                'ordering': ['student_code'],
                'indexes': [models.Index(fields=['student_code'], name='students_st_student_5e7a7e_idx'), models.Index(fields=['national_id'], name='students_st_nationa_fc49ba_idx')],
            },
        ),
    ]
