# Generated by Django 6.1.1 on 2026-10-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Ảnh đại diện hiển thị trên Dashboard', null=True, upload_to='avatars/students/'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_address',
            field=models.CharField(blank=True, help_text='Địa chỉ liên hệ hiện tại của sinh viên', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_link',
            field=models.URLField(blank=True, help_text='Liên kết hồ sơ cá nhân (LinkedIn, Portfolio... để nhà tuyển dụng xem)', max_length=255),
        ),
    ]
