# Generated by Django 6.1.1 on 2026-10-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_avatar_student_current_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp (Chưa duyệt)'), ('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt')], default='draft', help_text='Trạng thái phê duyệt cấp bằng', max_length=20),
        ),
    ]
