# Generated by Django 6.1.1 on 2026-10-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email này đã được sử dụng cho một sinh viên khác.'}, max_length=254, unique=True),
        ),
    ]
