# Generated by Django 5.0.14 on 2026-09-17 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('graduation', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('pdf_path', models.CharField(max_length=255)),
                ('template_version', models.CharField(max_length=20)),
                ('credential_version', models.CharField(max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('canonical_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('ISSUANCE_PENDING', 'Issuance Pending'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='DRAFT', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_degrees', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='graduation.graduationbatch')),
                ('degree_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.degreetype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_degrees', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='students.student')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='degrees.degree')),
            ],
        ),
    ]
