# Generated by Django 5.0.14 on 2026-09-17 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('degrees', '0001_initial'),
        ('graduation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merkle_root', models.CharField(blank=True, max_length=66, null=True)),
                ('chain_id', models.CharField(blank=True, max_length=50, null=True)),
                ('network_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('contract_version', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('graduation_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuance_batches', to='graduation.graduationbatch')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeMerkleProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf_hash', models.CharField(max_length=64)),
                ('leaf_index', models.IntegerField()),
                ('proof_path', models.JSONField()),
                ('degree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merkle_proof', to='degrees.degree')),
                ('issuance_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='blockchain.issuancebatch')),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('ISSUE', 'Issue'), ('RETRY', 'Retry'), ('REVOKE', 'Revoke'), ('SYNC', 'Sync')], max_length=20)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('gas_used', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='degrees.degree')),
                ('issuance_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.issuancebatch')),
            ],
        ),
    ]
