# Generated by Django 5.0.14 on 2026-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('decision_no', models.CharField(blank=True, max_length=50, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
