# Generated by Django 6.1.1 on 2026-09-17 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduationbatch',
            options={'verbose_name': 'Đợt tốt nghiệp', 'verbose_name_plural': 'Các đợt tốt nghiệp'},
        ),
        migrations.AddField(
            model_name='graduationbatch',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt'),
        ),
        migrations.AddField(
            model_name='graduationbatch',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_graduation_batches', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt (Checker)'),
        ),
        migrations.AddField(
            model_name='graduationbatch',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_graduation_batches', to=settings.AUTH_USER_MODEL, verbose_name='Người lập (Maker)'),
        ),
        migrations.AddField(
            model_name='graduationbatch',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do từ chối'),
        ),
        migrations.AddField(
            model_name='graduationbatch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='DRAFT', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='graduationbatch',
            name='decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày quyết định'),
        ),
        migrations.AlterField(
            model_name='graduationbatch',
            name='decision_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số quyết định'),
        ),
        migrations.AlterField(
            model_name='graduationbatch',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tên đợt tốt nghiệp'),
        ),
    ]
