# Generated by Django 6.1.1 on 2026-09-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0002_alter_graduationbatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationbatch',
            name='merkle_root',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Mã Merkle Root'),
        ),
        migrations.AddField(
            model_name='graduationbatch',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch Blockchain'),
        ),
    ]
